name: internal-maintenance-management

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: internal-maintenance-sqlserver-dev
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - internal_sqlserver_data_dev:/var/opt/mssql
    mem_limit: 1024m
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  internal_sqlserver_data_dev: